# -*- coding: utf-8 -*-
"""Nightlife Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_vO2KG29h6V9Iqz7YMtG9QD6DdrP0gDq
"""

#data with faker

import random
import faker

import pandas as pd
import datetime
from faker import Faker
fake_tr = Faker("tr_TR")
fake_en = Faker()
genress = ["r&b", "metal", "rock", "techno", "pop", "electronic", "blues", "jazz", "punk"]
provinces = ["taksim", "beşiktaş", "kadıköy", "beyoğlu", "levent", "bebek"]
province = []
venue = []
genreee = []
for i in range(500):
  venue.append(fake_en.domain_word())
  genreee.append(random.choice(genress))
  province.append(random.choice(provinces))

import re

f1 = open("artist_data.csv", "r")
artist = []
for celeb in f1:
  celeb_pp = str(celeb).lower()
  celeb_pp = re.sub("\n", "", celeb_pp)
  artist.append(celeb_pp)
artist[:10]

artist_genre_dict[""]

f2 = open("genre_data.csv", "r")
genre = []
for gen in f2:
  genre_pp = str(gen).lower()
  genre_pp = re.sub("\n", "", genre_pp)
  genre.append(genre_pp)
genre[:10]

artist_genre_dict = dict(zip(artist, genre))

from pandas._libs import index
fake_data = {"genre": genreee, "province":province}
nightlife_data = pd.DataFrame(fake_data, index=venue)

nightlife_data[:20]

pip install wit

from wit import Wit
access_token = "5O6MM3BQBVCZHYIV5OMCFPDOO3NTH3AG"
person = Wit(access_token)
person.message('Where can I listen to R&B in Taksim?')

#nightlife_data.loc[["cook"], ["genre"]]

def find_genre(place):
  """Finds the genre of a venue"""
  place = place.lower()
  return nightlife_data.loc[[place], ["genre"]]

def find_venue(string):
  """Finds venues given genre or province"""
  string = string.lower()
  if string in genress:
    return nightlife_data.loc[nightlife_data["genre"] == string]
  elif string in provinces:
    return nightlife_data.loc[nightlife_data["province"] == string]

def find_venue_gp(string1, string2):
  """Finds venues given genre and province"""
  string1 = string1.lower()
  string2 = string2.lower()
  if string1 in genress and string2 in provinces:
    return nightlife_data.loc[(nightlife_data["genre"] == string1) & (nightlife_data["province"] == string2)]
  """
  if string1 in genress:
    return nightlife_data.loc[nightlife_data["genre"] == string1]
  if string2 in provinces:
    return [nightlife_data["province"] == string2]
  """

find_venue_gp("rock", "levent")

find_venue("pop")

def InputAnalysis(text):
  """Finds the province and genre from the wit.ai output"""
  resp = person.message(text)
  if len(resp["entities"]) == 2:
    entity0 = list(resp["entities"])[0]
    value0 = resp["entities"][entity0][0]["value"]
    entity0 = re.sub(r"\w+:", "", entity0)
    entity1 = list(resp["entities"])[1]
    value1 = resp["entities"][entity1][0]["value"]
    entity1 = re.sub(r"\w+:", "", entity1)
    return ([entity0, value0, entity1, value1])
  elif len(resp["entities"]) == 1:
    entity0 = list(resp["entities"])[0]
    value0 = resp["entities"][entity0][0]["value"]
    entity0 = re.sub(r"\w+:", "", entity0)
    return ([entity0, value0])
InputAnalysis('Where can I listen rnb?')

message = "I want to listen rock in beşiktaş"
entity0, value0, entity1, value1 = InputAnalysis(message)

InputAnalysis("rnb in taksim")

find_venue_gp(value1, value0)

def NightBot(text):
  
  """bütün fonksiyonları birleştir"""
  returnlist = InputAnalysis(text)
  if len(returnlist) == 4:
    entity0, value0, entity1, value1 = InputAnalysis(text)
    result = find_venue_gp(value1, value0)
    bars = ",".join([str(i) for i in result.index.values])
    print(f"You can listen to {value1} in {value0} in these bars: {bars}")
  elif len(returnlist) == 2:
    entity0, value0 = InputAnalysis(text)
    result = find_venue(value0)
    bars = ",".join([str(i) for i in result.index.values])
    if entity0 =="province":
      print(f"These are the bars in {value0}: {bars}")
    else:
      print(f"You can listen to {value0} in these bars: {bars}")
